clone_folder: C:\LARCmaCS
shallow_clone: true

environment:
  global:
    MSYS_DIR: C:\msys64
    
  matrix:
    - platform: x86
      platform_name: i686
      MATLAB_DIR: C:\MCR\%platform%\extern
      bit: 32
    - platform: x64
      platform_name: x86_64
      MATLAB_DIR: C:\MCR\%platform%\extern
      bit: 64      

init:
  - set PATH=%PATH%;%MSYS_DIR%\usr\bin
  - git clone https://github.com/IKhonakhbeeva/MCR_for_LARCmaCS C:\MCR
  - pacman --noconfirm -Su mingw%bit%/mingw-w64-%platform_name%-gcc
  - pacman --noconfirm -Su mingw%bit%/mingw-w64-%platform_name%-make
  - pacman --noconfirm -Su mingw%bit%/mingw-w64-%platform_name%-qt5
  - pacman --noconfirm -Su mingw%bit%/mingw-w64-%platform_name%-protobuf
  
build_script:
  - set PATH=%MSYS_DIR%\mingw%bit%\bin;%PATH%;
  - mkdir C:\build_mingw_%platform%
  - cd C:\build_mingw_%platform%
  - qmake.exe C:\LARCmaCS\LARCmaCS.pro -spec win32-g++ "CONFIG+=release" "CONFIG+=qtquickcompiler" "MATLAB_DIR=%MATLAB_DIR%" "MSYS_DIR=%MSYS_DIR%" 
  - mingw32-make.exe qmake_all
  - mingw32-make.exe -j4